### ISSUE TITLE
TODO for first release

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/chorus#1]
- [x] remove debugging from nostr.rs
- [x] nostr.rs - make sure early errors reply to the caller with something, and improve that something as soon as we can
- [x] on nostr.rs::event(), scan subscriptions and send if filters match
- [x] nostr.rs::validate_event() should check signature (put option in config file)
- [x] output buffer length checking needs work
- [x] When fetching replaceable events, return only the latest.
- [x] finish testing in event_store.rs
- [x] event_store.rs should not just presume Out of Space, check better
- [x] verify all _be_ and _ne_ are correct. Fix json_event test FIXME about big-endian machines
- [x] AUTH
- [x] Restrict some REQs to require AUTH; Make sure I'm doing CLOSED with auth-required prefix on REQs that need auth (this turned out to not be necessary, we just don't supply such events)
- [x] Filter events loaded by REQ to unapproved users - only events authored by approved users, or a few other kinds.
- [x] Allow ephemeral events from everybody?
- [x] NIP-04 compliance (DM)
- [x] NIP-09 compliance (delete)
- [x] NIP-59 compliance (GiftWrap)
- [x] Banning at IP level
- [x] a natural ban of 4 seconds after any close.
- [x] Max subscriptions in config, 32 by default
- [x] User documentation describing configuration settings and relay behavior
